import Head from "next/head";
import about from "../public/styles/about.module.css";
import Image from "next/image";
import Footer from './components/_footer';


export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div>
          <img src="/image/about.svg" className={about.image}/>
          <div className={about.aboutheader}>
          <div className={about.aboutheadertitle}>
            <p className={about.titleheader}>About</p>
          </div>
          <div className={about.aboutheadertext}>
            <p className={about.titledetail}>DVN&apos;s story begins with the exploration of beauty inside and out for women. We believe that every woman has the right to define her own beauty, which is not only external but also stems from inner strength. At the same time, we are committed to encouraging women to bravely pursue their inner beauty and strength, free from any standards and definitions.</p>
          </div>
          </div>
        </div>
        <div>
          <Image src="/image/garis.png" width={1280} height={56}/>
        </div>
        <div className={about.tombol}>
        <button className={about.brand}>Brand</button>
        <button className={about.management}>Management</button>
        </div>
      </section>
      <section className={about.section}>
          <div className={about.col_one}>
            <div className={about.container_core}>
              <p className={about.core}><span className={about.black}>Core</span> Brand Values</p>
              <p className={about.value_core}>DVN&apos;s core values ​​lie in advocating the combination of beauty and strength, and encouraging women to unleash their inner beauty and power. We are dedicated to providing women with nutritional beauty solutions that not only focus on skincare but also help women achieve confident growth and influence.</p>
            </div>
          </div>
          <div className={about.col_two_color}>
            <Image src="/image/dvn_about.svg" className={about.dvn} width={295.7} height={149.27}/>
          </div>
      </section>
      <section className={about.section}>
          <div className={about.col_one}>
            <Image src="/image/duo.svg" className={about.duo} width={295.7} height={149.27} layout="responsive"/>
          </div>
          <div className={about.col_two}>
          <div className={about.container_core}>
              <p className={about.core}><span className={about.black}>Global Leading </span><br />Beauty Concept</p>
              <p className={about.value_core}>DVN adheres to the globally leading beauty concept, combining the concept of nutritional beauty with revolutionary skincare solutions, to bring women a comprehensive beauty experience from the inside out. Our products integrate top-notch patented technology globally, aiming to provide women with safe and effective beauty solutions.</p>
            </div>
          </div>
      </section>
      <section className={about.section}>
          <div className={about.col_one}>
          <div className={about.container_core}>
              <p className={about.core}><span className={about.black}>Brand</span><br /> Original Intention</p>
              <p className={about.value_core}>DVN&apos;s original intention is to offer women more choices, allowing them to confidently define their beauty and strength. We hope to inspire women&apos;s confidence and courage from within through our products and concepts, empowering them to be the masters of their own lives.</p>
            </div>
          </div>
          <div className={about.col_two}>
          <Image src="/image/botol_dvn.svg" className={about.botol_dvn} width={295.7} height={149.27} layout="responsive" />
          </div>
      </section>
      <section className={about.section}>
          <div className={about.col_one_image}>
          <div className={about.container_core}>
              <p className={about.core_down}>Brand Mission</p>
              <p className={about.value_core_down}>DVN&apos;s mission is to help women unleash their inner beauty and power through nutritional beauty solutions, enabling them to grow in confidence and bring about change through influence.</p>
            </div>
          {/* <Image src="/image/blur1.png" className={about.blur1} width={295.7} height={149.27}/> */}
          </div>
          <div className={about.col_two_image}>
          <div className={about.container_core}>
              <p className={about.core_down}>Brand Vision</p>
              <p className={about.value_core_down}>DVN&apos;s vision is to become a leader in women&apos;s beauty and strength, providing safe and effective nutritional beauty solutions for women worldwide, allowing them to shine in their self-defined beauty.</p>
            </div>
          {/* <Image src="/image/blur2.png" className={about.blur2} width={295.7} height={149.27}/> */}
          </div>
      </section>
      <section>
          <div className={about.section_five}>
            <div className={about.container_text_1}>
              <p className={about.text_1}><span className={about.text_black}>Brand</span> Advantages</p>
              <p className={about.text_2}>
              Leading Technology: We integrate top-notch patented technology globally, providing safe and effective nutritional beauty solutions.
              <br/><br/>
              Inner and Outer Balance: We focus on women&apos;s inner beauty and strength, striving to enhance women&apos;s overall beauty from the inside out.
              </p>
            </div>
            <div className={about.container_text_2}>
              <p className={about.text_1}><span className={about.text_black}>Brand</span> Philosophy</p>
              <p className={about.text_2}>
              We uphold the combination of beauty and strength, encouraging women to bravely pursue their inner beauty and strength, free from any standards and definitions.
              </p>
            </div>
            <div className={about.container_text_3}>
              <p className={about.text_1}><span className={about.text_black}>Customized</span><br/>Solution</p>
              <p lassName={about.text_2}>
              Our products and services are customized according to individual needs, meeting the beauty and health needs of different women.
              </p>
            </div>
            <img className={about.image_center} src="/image/dvn-group.png" />
          </div>
      </section>
    <Footer />
    </>
  );
}
