import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../public/styles/Home.module.css";
import CarouselComponent from "./components/_caraousel";
import Slides from "./components/_slide";
import Footer from "./components/_footer";
import PicturePudar from "./components/_picture_pudar";
import PerfectPage from "./components/_perfect";
import YouTubeEmbed from './components/_youtubeEmbed';
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DVN Scincare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <CarouselComponent />
      <img src="/image/awankirifooter.png" alt="" className={styles.awannya_caraousel}/>
      <img className={styles.cloud} src="/image/Cloud1.png" alt="caraousel 1" /> 
      <img src="/image/garis.png" alt="caraousel 1" width="100%" />
      <Slides />
      <PerfectPage />
      <section className={styles.youtube}>
        <div className={styles.containerText}>
            <span className={styles.span}>Do you <span className={styles.know}>Know?</span> </span> <span className={styles.descript}>Uneven skin tone is a major problem for women.</span>
        </div>
        <div className={styles.video}>
        <YouTubeEmbed videoId="IKCSNNeRTDA" thumbnailUrl="image/youtube.png" />
        </div>
      </section>
      <section>
        <div className={styles.badfactor}>
        <img src="/image/image.png"/>
        </div>
      </section>
      <PicturePudar />
      <div>
      <Footer />
      </div>
    </>
  );
}
