import Head from 'next/head';
import { useTranslation } from 'next-i18next';
import styles from '@/styles/Home.module.css';
import CarouselComponent from './components/_caraousel';
import Slides from './components/_slide';
import Footer from './components/_footer';
import PicturePudar from './components/_picture_pudar';
import PerfectPage from './components/_perfect';
import YouTubeEmbed from './components/_youtubeEmbed';
import Burger from './components/_burger';

const Home = () => {
  const { t } = useTranslation('common');

  return (
    <>
      <Head>
        <title>DVN Skincare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CarouselComponent />
      <Burger />
      <img src="/image/awan-home-kiri.png" alt="" className={styles.awannya_caraousel} />
      <img className={styles.cloud} src="/image/Cloud1.png" alt="caraousel 1" />
      <img src="/image/garis.png" className={styles.garis} alt="caraousel 1" width="100%" />
      <Slides />
      <PerfectPage />
      <section className={styles.youtube}>
      <div className={styles.containerText}>
            <span className={styles.span} suppressHydrationWarning>{t('do you')} <span className={styles.know} suppressHydrationWarning>{t('know')}</span> <br className={styles.know_br}/> </span> <span className={styles.descript} suppressHydrationWarning>{t('uneven')}</span>
        </div>
        <div className={styles.video}>
          <YouTubeEmbed videoId="IKCSNNeRTDA" thumbnailUrl="image/youtube.png" />
        </div>
      </section>
      <section>
        <div className={styles.badfactor}>
          <img src="/image/image.png" />
        </div>
      </section>
      <PicturePudar />
      <Footer />
    </>
  );
};

export default Home;
