import Head from "next/head";
import Footer from './components/_footer';
import FormJoin from './components/_join_dealers';

export default function Home() {
  return (
    <>
      <Head>
        <title>DVN Scincare - Join Dealers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <FormJoin />
    </>
  );
}
